language: php
sudo: false

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - $HOME/.php-cs-fixer
  - $HOME/.local
env:
  global:
  - CC_TEST_REPORTER_ID=ff208c24a9f196d9bfc66a49f6bf8592a07e82c6eed47ea481e299c4c648e393
  - RUN_WITH_COVERAGE=false

matrix:
  fast_finish: true
  include:
  - php: 7.3
    env: EXECUTE_CS_CHECK=true RUN_WITH_COVERAGE=true PATH="$HOME/.local/bin:$PATH"
  - php: 7.3
  - php: 7.4
  - php: nightly
  allow_failures:
  - php: 7.4
  - php: nightly

before_install:
  - ./build/script/travis_before_install.sh

install:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --optimize-autoloader  --profile --no-interaction

script:
  - ./build/script/travis_script.sh

after_success:
  - ./build/script/travis_after_success.sh

notifications:
  email: false
  slack:
    secure: JqH3MeraT5uwvV+Qh+wzjIbo0y7A7ltisIgnJjdT94EVjI94p52HHMB3ABh5/aJ/KMXtcFNov9x5G60+6UztOqHLNYiToOy3PACtz99yEOt5aniAtut9Ne9xaII06KMErCt04cYMl0tTBYiXvzc16GThZ8tEnx+2Hmr5Craj2qn90sWSFMMi2zpyJWAo9UU9cRgYuVy/KGP3Qji3GUe7yXpDMZD4BT5DFr0nr5P/CiJZnnIzseB6LP8A/t9FF2wYnVTyjB9uR+q+A40s7dZ2SSxN/PCi853acJDcozg5uxXaA4RMFVBILzGrWncLl72rxayq8fg4376rEFCFcQBv3lSZN2RwZVbiZIukZ6n3ZDoe+nXJ/9irBH/8drJuDUssIlVVzu8oZ0OzCmpmvpCovy7XToUiTlkEQYc4nvTMgVa9GlmjhevEDLSsS+1qouFmlb8oXsh2rBhRVXUMXTN6VxD3uDFXYvswhcmGNYA5xkH0f1VrgYBqAYjUgKQ1H05Y5zguMSdbcPQsMJd4ZsI8Z/vEZcPoonfCD+nAH0HTVxxD4JVN/4H3lfaF+rNelBMZN/s5JX8DF3+5FQqFqVRyCZ6S+7CMY2M7YZbNx+rnxmm3J+th93p4AWHE1TRJbsiZhStDm9IpUDDoxvng8ebT2bEyLRITVmZ1Hld//AN3/OI=
